export const CHANGE_INPUT_VALUE = 'change_input_item'
export const ADD_TODO_ITEM = 'add_todo_item'
export const DELETE_TO_ITEM = 'delete_todo_item'
export const INIT_LIST_ACTION = 'init_list_action'
export const GET_INIT_LIST = 'get_init_list'